version: '3.7'

# Define services
services:

  # Frontend Service
  frontend:
    container_name: frontend
    build:
      context: ${FRONTEND_PROJECT_PATH:-.}
      dockerfile: Dockerfile
      target: DEV_ENV
      args:
        ANGULAR_APP_API_BASE_URL: http://127.0.0.1:8080/api
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    ports:
      - 4200:4200
    restart: always
    working_dir: /app
    user: node
    command: npm start -- --host 0.0.0.0 --port 4200
    volumes:
      - ${FRONTEND_PROJECT_PATH:-.}/:/app
      - /app/node_modules
      # - ${FRONTEND_PROJECT_PATH:-.}/node_modules:/app/node_modules
    networks:
      - devnet

# Networks to be created to facilitate communication between containers
networks:
  devnet:
    driver: bridge
